package org.gcit.enums;

public enum ConfigProperties {
    URL,
    OVERRIDEREPORTS,
    PASSEDSTEPSCREENSHOT,
    FAILEDSTEPSCREENSHOT,
    SKIPPEDSTEPSCREENSHOT,
    RETRY,
    BROWSER,
    RETRYATTEMPTS,
    ENV,
    DATASOURCE,
    EXPLICITWAITTIMEOUT,
    BROWSERHEADLESSMODE,
    SELENIUMGRIDADDRESS,
    RUNMODE;
}
